services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

#  app:
#    build: .
#    command: fastapi dev
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - .env

volumes:
  pgdata:
